### PR TITLE
Add missed variables

### PR DESCRIPTION
**Pull request by drama17**
## What
* Add variables missed in `variables.tf`

## Why
* Getting errors when trying to use this module:

_An argument named "namespace" is not expected here._
_An argument named "stage" is not expected here._

### CODE REVIEW

**Comment by maximmi** [comment]
@drama17 please, check that you are not providing `namespace` and `stage` arguments using `.tfvars` or `TF_VAR_` environment variable. 
There is no need for such arguments in this module!

**Comment by it-svit** [comment]
> @drama17 please, check that you are not providing `namespace` and `stage` arguments using `.tfvars` or `TF_VAR_` environment variable.
> There is no need for such arguments in this module!

This module is using in `terraform-aws-ec2-bastion-server` module - https://github.com/cloudposse/terraform-aws-ec2-bastion-server/blob/master/main.tf#L107
As you can see, there are no such variables in https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/blob/master/variables.tf which cause an error. @maximmi

**Comment by drama17** [comment]
> @drama17 please, check that you are not providing `namespace` and `stage` arguments using `.tfvars` or `TF_VAR_` environment variable.
> There is no need for such arguments in this module!

This module is using in `terraform-aws-ec2-bastion-server` module - https://github.com/cloudposse/terraform-aws-ec2-bastion-server/blob/master/main.tf#L107
As you can see, there are no such variables in https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/blob/master/variables.tf which cause an error. @maximmi

**Comment by drama17** [comment]
But.. I see what you mean and agree. And I think it is better to remove `namespace = "${var.namespace}"` and `stage     = "${var.stage}"` from https://github.com/cloudposse/terraform-aws-ec2-bastion-server/blob/master/main.tf#L107

**Comment by maximmi** [comment]
> > @drama17 please, check that you are not providing `namespace` and `stage` arguments using `.tfvars` or `TF_VAR_` environment variable.
> > There is no need for such arguments in this module!
> 
> This module is using in `terraform-aws-ec2-bastion-server` module - https://github.com/cloudposse/terraform-aws-ec2-bastion-server/blob/master/main.tf#L107
> As you can see, there are no such variables in https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/blob/master/variables.tf which cause an error. @maximmi

@drama17 As you can see `terraform-aws-ec2-bastion-server` points to `0.2.5` tag of `terraform-aws-route53-cluster-hostname` and `https://github.com/cloudposse/terraform-aws-route53-cluster-hostname/blob/0.2.5/variables.tf` have both `namespace` and `stage`

**Comment by it-svit** [comment]
My bad. Missed when was redirected on master checking `terraform-aws-route53-cluster-hostname`

**Pull request closed without merging**
