### PR TITLE
Upgrade to Terraform 0.12

### PR DESCRIPTION
**Pull request by kjagiello**

### CODE REVIEW

**Comment by stefansedich** [comment]
Any chance of getting these merged? the final piece of our upgrade puzzle to get away from our forks.

**Comment by stefansedich** [comment]
Any chance of getting this merged? the final piece of our upgrade puzzle to get away from our forks.

**Comment by stefansedich** [comment]
I opened up another PR with the upgrade and also getting the build passing @kjagiello, you can either add my changes into your PR and I can close mine or we can just go with the mine.

**Comment by kjagiello** [comment]
Nice one! Let's go with yours 🙌

**Pull request closed without merging**
